#pragma once

enum EColliderType
{
	E_COLLIDER_TYPE_INVALID = -1,
	E_COLLIDER_TYPE_INIT = 0,

	E_COLLIDER_TYPE_PLANE,
	E_COLLIDER_TYPE_SPHERE,
	E_COLLIDER_TYPE_BOX,
	E_COLLIDER_TYPE_CAPSULE,
	E_COLLIDER_TYPE_MESH,
	
	E_COLLIDER_TYPE_END,
};

enum EPLaneColliderAxis
{
	E_PLANE_COLLIDER_AXIS_INIT = 0,

	E_PLANE_COLLIDER_AXIS_X,
	E_PLANE_COLLIDER_AXIS_Y,
	E_PLANE_COLLIDER_AXIS_Z,
};

