#pragma once

DEF_MSG_START(EMessageID)

	//create account
	DEF_C2S_ITEM(C2S_REGISTER)
	DEF_S2C_ITEM(S2C_REGISTER_RESP)

	//login
	DEF_C2S_ITEM(C2S_AUTHENTICATE)
	DEF_S2C_ITEM(S2C_AUTHENTICATE_RESP)

	//join room
	DEF_C2S_ITEM(C2S_JOIN_ROOM)
	DEF_S2C_ITEM(S2C_JOIN_ROOM_RESP)

	//leave room
	DEF_C2S_ITEM(C2S_LEAVE_ROOM)
	DEF_S2C_ITEM(S2C_LEAVE_ROOM_RESP)

	//chat
	DEF_C2S_ITEM(C2S_CHAT)
	DEF_C2S_ITEM(S2C_CHAT_RESP)
	DEF_S2C_ITEM(S2C_BROADCAST)

	//Create Account
	DEF_MSG_ITEM(S2A_CREATE_ACCOUNT)
	DEF_MSG_ITEM(A2S_CREATE_ACCOUNT_RESP)

	//Authenticate
	DEF_MSG_ITEM(S2A_AUTHENTICATE)
	DEF_MSG_ITEM(A2S_AUTHENTICATE_RESP)

	DEF_MSG_ITEM(MSG_END)	//add message id above this

DEF_MSG_END



